### PR TITLE
Add filter for altering the list of excluded custom post types for th…

### PR DESCRIPTION
**Pull request by greenhornet79**
…e rating widget display

### CODE REVIEW

**Comment by vovafeldman** [comment]
@greenhornet79 Thanks for the PR - good filter! Will be deployed to our next .org release.

**Comment by greenhornet79** [comment]
@vovafeldman Thanks. I actually added it to the premium version of your plugin on a client's site because I needed it. Would you mind adding the filter to that version of the plugin as well?

**Comment by vovafeldman** [comment]
We are using [Freemius](https://freemius.com) for deployment, so It will be automatically added to both version.

Would you mind sharing what was the use-case? What post types your customer wanted to exclude?

**Comment by greenhornet79** [comment]
They had an FAQ that didn't want to display the reviews widget on. They have hundreds of entries, so it didn't make sense to hide them on an individual post basis.

**Pull request merged**
